-- 구성
-- INSERT INTO GROUPS 
-- VALUES(SEQ_GROUP_NO.NEXTVAL,group_leader(user_no),group_name);



INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,1,'강라빈팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,1,'손월변팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,1,'길뜸흔팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,1,'용헌령팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,2,'소송휘팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,2,'고배제팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,2,'육무늬팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,2,'채달지팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,3,'인미호팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,3,'고대지팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,3,'강미술팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,3,'정일려팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,4,'송악환팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,4,'황학디팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,4,'류항호팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,4,'배비양팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,5,'채용숭팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,5,'함소완팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,5,'편변유팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,5,'위나건팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,6,'허아덕팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,6,'제란배팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,6,'여슬평팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,6,'공훔정팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,7,'우두배팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,7,'소웅빛팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,7,'구란민팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,7,'추석찬팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,8,'은숭여팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,8,'신추판팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,8,'채민찬팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,8,'고새평팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,9,'하훔아팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,9,'조설해팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,9,'이빛누팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,9,'진세형팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,10,'안대오팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,10,'차무웅팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,10,'노도환팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,10,'류해석팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,11,'은장려팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,11,'설겸랑팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,11,'신일란팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,11,'기채별팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,12,'왕산섬팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,12,'방디원팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,12,'금술을팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,12,'고늬문팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,13,'차잎경팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,13,'제희관팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,13,'노효탁팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,13,'천복정팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,14,'용늬초팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,14,'김환예팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,14,'하권오팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,14,'노조고팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,15,'민루구팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,15,'변균향팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,15,'위구루팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,15,'양누희팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,16,'심욱린팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,16,'인단다팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,16,'고시상팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,16,'인출숭팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,17,'추만항팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,17,'엄안고팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,17,'왕순림팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,17,'임옥화팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,18,'송걸대팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,18,'변영디팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,18,'우부석팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,18,'기령예팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,19,'은기석팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,19,'방규춘팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,19,'백공봉팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,19,'옥율홍팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,20,'장빈로팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,20,'남량라팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,20,'노섭열팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,20,'남반서팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,21,'신손순팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,21,'홍공훔팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,21,'금운범팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,21,'남아솜팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,22,'금배근팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,22,'남길규팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,22,'제가산팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,22,'강하비팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,23,'황한달팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,23,'선택선팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,23,'왕평율팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,23,'장개양팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,24,'용자연팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,24,'손현복팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,24,'신상루팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,24,'강빈분팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,25,'원월형팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,25,'권로노팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,25,'어미균팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,25,'고라소팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,26,'주후부팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,26,'성령숭팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,26,'진빛현팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,26,'문직율팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,27,'민권언팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,27,'장뜸성팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,27,'우면백팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,27,'마구심팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,28,'노송소팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,28,'진부기팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,28,'오얀향팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,28,'장택잎팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,29,'제부상팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,29,'김도림팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,29,'조윤준팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,29,'연림나팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,30,'현범장팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,30,'노겸도팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,30,'여홍순팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,30,'노선관팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,31,'신일라팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,31,'변배숙팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,31,'하랑혁팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,31,'강석덕팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,32,'곽학판팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,32,'양바창팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,32,'양병이팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,32,'탁솜수팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,33,'기보길팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,33,'육령원팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,33,'서려으팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,33,'이춘산팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,34,'나동흥팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,34,'권림늘팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,34,'금바신팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,34,'남윤숙팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,35,'위묵예팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,35,'백섭면팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,35,'임보태팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,35,'곽민부팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,36,'반로이팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,36,'현회월팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,36,'신흠헌팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,36,'진령걸팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,37,'인랑라팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,37,'백철심팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,37,'조범솔팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,37,'허택란팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,38,'구남산팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,38,'서승흠팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,38,'허면바팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,38,'은근율팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,39,'모겸누팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,39,'육장령팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,39,'염주해팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,39,'하병훔팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,40,'국광달팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,40,'설균춘팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,40,'하람솜팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,40,'신악산팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,41,'석걸안팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,41,'도엽천팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,41,'위늬평팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,41,'길용영팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,42,'금별도팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,42,'장춘기팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,42,'강건창팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,42,'전온구팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,43,'모우출팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,43,'곽회향팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,43,'신곤운팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,43,'표철손팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,44,'강산비팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,44,'변누현팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,44,'연출섭팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,44,'설성탁팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,45,'방수탁팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,45,'최견으팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,45,'윤서두팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,45,'노은람팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,46,'민선담팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,46,'신사마팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,46,'차련태팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,46,'변수정팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,47,'마림숭팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,47,'진술흔팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,47,'채잔재팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,47,'류홍개팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,48,'노헌나팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,48,'장광실팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,48,'신울권팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,48,'공환범팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,49,'여신범팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,49,'백규박팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,49,'윤승율팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,49,'송중효팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,50,'진변잔팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,50,'유윤빈팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,50,'변섬복팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,50,'구다강팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,51,'남나양팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,51,'함빛혼팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,51,'국실설팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,51,'문직악팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,52,'최민휴팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,52,'유제리팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,52,'안보항팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,52,'육성두팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,53,'윤혜병팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,53,'기율욱팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,53,'편치봉팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,53,'서원가팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,54,'강번철팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,54,'손균고팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,54,'원묵태팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,54,'조오을팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,55,'여훈남팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,55,'백경항팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,55,'황철위팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,55,'옥심빈팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,56,'제려주팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,56,'임양추팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,56,'노달누팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,56,'나용진팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,57,'박리손팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,57,'구규예팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,57,'임율판팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,57,'장세린팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,58,'원신혜팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,58,'박전웅팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,58,'반규위팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,58,'류여봉팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,59,'박량원팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,59,'맹혜복팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,59,'도랑근팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,59,'남라재팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,60,'장솔실팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,60,'정엄춘팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,60,'금민남팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,60,'육미혜팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,61,'윤란홍팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,61,'강미탐팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,61,'은부언팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,61,'진직번팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,62,'오가종팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,62,'최린심팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,62,'하반양팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,62,'명병사팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,63,'홍달휴팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,63,'노장려팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,63,'은려탁팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,63,'한을규팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,64,'진종언팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,64,'민도현팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,64,'강평기팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,64,'남평흔팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,65,'엄림건팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,65,'나경찬팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,65,'공백산팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,65,'옥권희팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,66,'양명강팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,66,'서가복팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,66,'장남탐팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,66,'강모기팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,67,'한혜원팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,67,'구령무팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,67,'신상춘팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,67,'채나판팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,68,'인엄흔팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,68,'안세잔팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,68,'구련요팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,68,'홍항려팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,69,'임사노팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,69,'임종란팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,69,'은택바팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,69,'맹린랑팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,70,'배일고팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,70,'마오병팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,70,'용솔문팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,70,'마지다팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,71,'마평균팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,71,'함위민팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,71,'남광탐팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,71,'정성롱팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,72,'함석잎팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,72,'유장기팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,72,'윤현걸팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,72,'권더솜팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,73,'임악훈팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,73,'하윤운팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,73,'강도아팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,73,'여노롱팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,74,'탁걸을팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,74,'맹여명팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,74,'윤준명팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,74,'지익탁팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,75,'한유제팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,75,'하조탁팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,75,'석충요팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,75,'허람요팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,76,'진천박팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,76,'최원위팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,76,'추영소팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,76,'추고려팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,77,'전공령팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,77,'금연화팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,77,'추변석팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,77,'여여다팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,78,'용오루팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,78,'현비명팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,78,'신혁찬팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,78,'손광학팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,79,'제려율팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,79,'명삼비팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,79,'소중타팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,79,'지혼곤팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,80,'어후양팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,80,'민건영팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,80,'여훔희팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,80,'조랑익팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,81,'기들개팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,81,'왕채더팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,81,'원잔바팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,81,'육잎악팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,82,'곽용유팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,82,'천사엽팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,82,'금창안팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,82,'손판솜팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,83,'설균헌팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,83,'강타걸팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,83,'신상산팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,83,'성평묵팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,84,'육얀채팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,84,'석해고팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,84,'손황광팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,84,'전손회팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,85,'임덕관팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,85,'육빛휘팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,85,'이규자팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,85,'한후요팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,86,'육섭수팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,86,'곽흥범팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,86,'유미분팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,86,'남옥백팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,87,'송배직팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,87,'노양선팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,87,'국무곤팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,87,'길안철팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,88,'마홍언팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,88,'선채초팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,88,'양현길팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,88,'현더대팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,89,'차해제팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,89,'편전직팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,89,'강은엽팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,89,'심량환팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,90,'오흠상팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,90,'인서양팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,90,'설익다팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,90,'배웅솜팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,91,'추순욱팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,91,'현개휘팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,91,'유원별팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,91,'송들랑팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,92,'남걸람팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,92,'연건강팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,92,'민량늘팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,92,'백누은팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,93,'송울유팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,93,'신화악팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,93,'편디택팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,93,'제섭항팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,94,'고휘로팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,94,'설조실팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,94,'조회탁팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,94,'민기원팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,95,'변잔울팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,95,'연항달팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,95,'은영아팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,95,'채덕별팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,96,'나기래팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,96,'진홍하팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,96,'류충일팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,96,'인병슬팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,97,'공용섬팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,97,'고춘섬팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,97,'기달출팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,97,'류추사팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,98,'양원관팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,98,'탁헌모팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,98,'김사묵팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,98,'양탐노팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,99,'이언삼팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,99,'진송서팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,99,'류림원팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,99,'강번열팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,100,'장더진팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,100,'천균개팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,100,'오늬섭팀');

INSERT INTO GROUPS 
VALUES(SEQ_GROUP_NO.NEXTVAL,100,'강환요팀');

commit;