INSERT INTO noti_no VALUES (1, '그룹 초대(초대받은 유저)');
INSERT INTO noti_no VALUES (2, '그룹 초대 수락(그룹장)');
INSERT INTO noti_no VALUES (3, '그룹 초대 거절(그룹장)');
INSERT INTO noti_no VALUES (4, '그룹원 탈퇴(그룹장)');
INSERT INTO noti_no VALUES (5, '그룹 강퇴(강퇴당한 유저)');
INSERT INTO noti_no VALUES (6, '그룹장 위임(현재 그룹장)');
INSERT INTO noti_no VALUES (7, '그룹명 변경(그룹장 제외)');
INSERT INTO noti_no VALUES (8, '신고된 리뷰 삭제');
INSERT INTO noti_no VALUES (9, '문의 답변(문의 작성자)');
INSERT INTO noti_no VALUES (10, '그룹 부장님 초대(초대받은 유저)');
